name: daVinci-local-infra

services:
  redis:
    image: redis:7.2
    container_name: daVinci-redis
    ports:
      - "6379:6379"
    volumes:
      - daVinci-redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 30s
      retries: 3
  mysql:
    image: mysql:8.4
    container_name: daVinci-mysql
    ports:
      - "3306:3306"
    volumes:
      - daVinci-mysql-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: daVinci_toss
      TZ: UTC
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s

volumes:
  daVinci-redis-data:
  daVinci-mysql-data:
