export { default as brainImg } from "./brain.webp";
export { default as logoImg } from "./logo.webp";
export { default as logoMarkImg } from "./logo_mark.webp";
export { default as painterMan1Img } from "./painter_man1.webp";
export { default as painterMan2Img } from "./painter_man2.webp";
export { default as paletteImg } from "./palette.webp";
export { default as penCircleImg } from "./pen_circle.webp";
export { default as thumbnailImg } from "./thumbnail.webp";
export { default as landing } from "./landing.webp";
